// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/web3eye-io/cyber-tracer/nft-meta/pkg/db/ent/blocknumber"
	"github.com/web3eye-io/cyber-tracer/nft-meta/pkg/db/ent/predicate"
)

// BlockNumberDelete is the builder for deleting a BlockNumber entity.
type BlockNumberDelete struct {
	config
	hooks    []Hook
	mutation *BlockNumberMutation
}

// Where appends a list predicates to the BlockNumberDelete builder.
func (bnd *BlockNumberDelete) Where(ps ...predicate.BlockNumber) *BlockNumberDelete {
	bnd.mutation.Where(ps...)
	return bnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bnd *BlockNumberDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bnd.hooks) == 0 {
		affected, err = bnd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BlockNumberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bnd.mutation = mutation
			affected, err = bnd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bnd.hooks) - 1; i >= 0; i-- {
			if bnd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bnd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bnd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bnd *BlockNumberDelete) ExecX(ctx context.Context) int {
	n, err := bnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bnd *BlockNumberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: blocknumber.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: blocknumber.FieldID,
			},
		},
	}
	if ps := bnd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bnd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// BlockNumberDeleteOne is the builder for deleting a single BlockNumber entity.
type BlockNumberDeleteOne struct {
	bnd *BlockNumberDelete
}

// Exec executes the deletion query.
func (bndo *BlockNumberDeleteOne) Exec(ctx context.Context) error {
	n, err := bndo.bnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{blocknumber.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bndo *BlockNumberDeleteOne) ExecX(ctx context.Context) {
	bndo.bnd.ExecX(ctx)
}
