apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kube-system
  name: entrance-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-entrance-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-http-redirect-https-testing@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - "*.testnet.web3eye.io"
        - testnet.web3eye.io
      secretName: testnet-web3eye-io-tls
  rules:
    - host: testnet.web3eye.io
      http:
        paths:
          - path: /api/entrance/v1/get/contract/and/tokens
            pathType: Prefix
            backend:
              service:
                name: entrance
                port:
                  number: 30150
          - path: /api/entrance/v1/get/token
            pathType: Prefix
            backend:
              service:
                name: entrance
                port:
                  number: 30150
          - path: /api/entrance/v1/search/page
            pathType: Prefix
            backend:
              service:
                name: entrance
                port:
                  number: 30150
          - path: /api/entrance/search/file
            pathType: Prefix
            backend:
              service:
                name: entrance
                port:
                  number: 30150
          - path: /api/entrance/v1/get/transfers
            pathType: Prefix
            backend:
              service:
                name: entrance
                port:
                  number: 30150
