---
- hosts: all

  tasks:
    - name: set-gateway
      shell: |
        gateway={{CLUSTER_GATEWAY}}
        set +e
        ip a |grep $gateway
        if [ $? -eq 0 ]; then
          exit 0
        fi
        set -e
        ip_sub=`echo $gateway | sed 's/.[0-9]$/0/g'`
        nic=`ip route |grep $ip_sub |awk '{print $3}'`
        netplan set ethernets.$nic.gateway4=$gateway
        netplan apply