apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: image-converter
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-converter
  template:
    metadata:
      labels:
        app: image-converter
    spec:
      containers:
        - name: image-converter
          # image: web3eye/image-converter:latest
          image: coastlinesss/image-converter:latest
          imagePullPolicy: Always
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: minio_access_key
              valueFrom:
                secretKeyRef:
                  name: web3eye-minio
                  key: accesskey
            - name: minio_secret_key
              valueFrom:
                secretKeyRef:
                  name: web3eye-minio
                  key: secretkey
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: image-converter
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: image-converter
