apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: coastlinesss/converter:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/Converter
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: converter-config
---
apiVersion: v1
kind: Service
metadata:
  name: converter
  namespace: kube-system
spec:
  selector:
    app: converter
  # clusterIP: None
  ports:
    - name: http
      port: 30190
      targetPort: 30190
    - name: grpc
      port: 30191
      targetPort: 30191
