apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: kube-system
  name: strip-cloud-proxy-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/cloud-proxy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kube-system
  name: cloud-proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # traefik.ingress.kubernetes.io/router.middlewares:
    #   kube-system-strip-cloud-proxy-prefix@kubernetescrd,
    #   kube-system-http-redirect-https@kubernetescrd,
    #   kube-system-http-redirect-https-testing@kubernetescrd,
    #   kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - "*.web3eye.webui.io"
        - web3eye.webui.io
      secretName: web3eye-webui-io-tls
  rules:
    - host: cloud-proxy.web3eye.webui.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-proxy
                port:
                  number: 30121
