apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: kube-system
  name: strip-cloud-proxy-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/cloud-proxy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kube-system
  name: cloud-proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  rules:
    - host: cloud-proxy.web3eye.io
      http: &http_rules
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-proxy
                port:
                  number: 30121
    - host: cloud-proxy.npool.top
      http: *http_rules
    - host: cloud-proxy.web3eye.npool.top
      http: *http_rules
