apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-etl
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-etl
  template:
    metadata:
      labels:
        app: block-etl
    spec:
      containers:
        - name: block-etl
          image: uhub.service.ucloud.cn/web3eye/block-etl:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/BlockETL
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password
      volumes:
        - name: service-config
          configMap:
            name: block-etl-config
---
apiVersion: v1
kind: Service
metadata:
  name: block-etl
  namespace: kube-system
spec:
  selector:
    app: block-etl
  # clusterIP: None
  ports:
    - name: http
      port: 30110
      targetPort: 30110
    - name: grpc
      port: 30111
      targetPort: 30111
