// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: web3eye/ranker/v1/synctask/synctask.proto

package synctask

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerClient interface {
	CreateSyncTask(ctx context.Context, in *CreateSyncTaskRequest, opts ...grpc.CallOption) (*CreateSyncTaskResponse, error)
	UpdateSyncTask(ctx context.Context, in *UpdateSyncTaskRequest, opts ...grpc.CallOption) (*UpdateSyncTaskResponse, error)
	GetSyncTask(ctx context.Context, in *GetSyncTaskRequest, opts ...grpc.CallOption) (*GetSyncTaskResponse, error)
	GetSyncTasks(ctx context.Context, in *GetSyncTasksRequest, opts ...grpc.CallOption) (*GetSyncTasksResponse, error)
	DeleteSyncTask(ctx context.Context, in *DeleteSyncTaskRequest, opts ...grpc.CallOption) (*DeleteSyncTaskResponse, error)
}

type managerClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerClient(cc grpc.ClientConnInterface) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) CreateSyncTask(ctx context.Context, in *CreateSyncTaskRequest, opts ...grpc.CallOption) (*CreateSyncTaskResponse, error) {
	out := new(CreateSyncTaskResponse)
	err := c.cc.Invoke(ctx, "/ranker.v1.synctask.Manager/CreateSyncTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) UpdateSyncTask(ctx context.Context, in *UpdateSyncTaskRequest, opts ...grpc.CallOption) (*UpdateSyncTaskResponse, error) {
	out := new(UpdateSyncTaskResponse)
	err := c.cc.Invoke(ctx, "/ranker.v1.synctask.Manager/UpdateSyncTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetSyncTask(ctx context.Context, in *GetSyncTaskRequest, opts ...grpc.CallOption) (*GetSyncTaskResponse, error) {
	out := new(GetSyncTaskResponse)
	err := c.cc.Invoke(ctx, "/ranker.v1.synctask.Manager/GetSyncTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetSyncTasks(ctx context.Context, in *GetSyncTasksRequest, opts ...grpc.CallOption) (*GetSyncTasksResponse, error) {
	out := new(GetSyncTasksResponse)
	err := c.cc.Invoke(ctx, "/ranker.v1.synctask.Manager/GetSyncTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeleteSyncTask(ctx context.Context, in *DeleteSyncTaskRequest, opts ...grpc.CallOption) (*DeleteSyncTaskResponse, error) {
	out := new(DeleteSyncTaskResponse)
	err := c.cc.Invoke(ctx, "/ranker.v1.synctask.Manager/DeleteSyncTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
// All implementations must embed UnimplementedManagerServer
// for forward compatibility
type ManagerServer interface {
	CreateSyncTask(context.Context, *CreateSyncTaskRequest) (*CreateSyncTaskResponse, error)
	UpdateSyncTask(context.Context, *UpdateSyncTaskRequest) (*UpdateSyncTaskResponse, error)
	GetSyncTask(context.Context, *GetSyncTaskRequest) (*GetSyncTaskResponse, error)
	GetSyncTasks(context.Context, *GetSyncTasksRequest) (*GetSyncTasksResponse, error)
	DeleteSyncTask(context.Context, *DeleteSyncTaskRequest) (*DeleteSyncTaskResponse, error)
	mustEmbedUnimplementedManagerServer()
}

// UnimplementedManagerServer must be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (UnimplementedManagerServer) CreateSyncTask(context.Context, *CreateSyncTaskRequest) (*CreateSyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSyncTask not implemented")
}
func (UnimplementedManagerServer) UpdateSyncTask(context.Context, *UpdateSyncTaskRequest) (*UpdateSyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSyncTask not implemented")
}
func (UnimplementedManagerServer) GetSyncTask(context.Context, *GetSyncTaskRequest) (*GetSyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyncTask not implemented")
}
func (UnimplementedManagerServer) GetSyncTasks(context.Context, *GetSyncTasksRequest) (*GetSyncTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyncTasks not implemented")
}
func (UnimplementedManagerServer) DeleteSyncTask(context.Context, *DeleteSyncTaskRequest) (*DeleteSyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSyncTask not implemented")
}
func (UnimplementedManagerServer) mustEmbedUnimplementedManagerServer() {}

// UnsafeManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServer will
// result in compilation errors.
type UnsafeManagerServer interface {
	mustEmbedUnimplementedManagerServer()
}

func RegisterManagerServer(s grpc.ServiceRegistrar, srv ManagerServer) {
	s.RegisterService(&Manager_ServiceDesc, srv)
}

func _Manager_CreateSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CreateSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranker.v1.synctask.Manager/CreateSyncTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CreateSyncTask(ctx, req.(*CreateSyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_UpdateSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranker.v1.synctask.Manager/UpdateSyncTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateSyncTask(ctx, req.(*UpdateSyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranker.v1.synctask.Manager/GetSyncTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetSyncTask(ctx, req.(*GetSyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetSyncTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetSyncTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranker.v1.synctask.Manager/GetSyncTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetSyncTasks(ctx, req.(*GetSyncTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeleteSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeleteSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranker.v1.synctask.Manager/DeleteSyncTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeleteSyncTask(ctx, req.(*DeleteSyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Manager_ServiceDesc is the grpc.ServiceDesc for Manager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranker.v1.synctask.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSyncTask",
			Handler:    _Manager_CreateSyncTask_Handler,
		},
		{
			MethodName: "UpdateSyncTask",
			Handler:    _Manager_UpdateSyncTask_Handler,
		},
		{
			MethodName: "GetSyncTask",
			Handler:    _Manager_GetSyncTask_Handler,
		},
		{
			MethodName: "GetSyncTasks",
			Handler:    _Manager_GetSyncTasks_Handler,
		},
		{
			MethodName: "DeleteSyncTask",
			Handler:    _Manager_DeleteSyncTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web3eye/ranker/v1/synctask/synctask.proto",
}
