apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealer
  template:
    metadata:
      labels:
        app: dealer
    spec:
      containers:
        - name: dealer
          image: uhub.service.ucloud.cn/web3eye/dealer:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/dealer
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password
            - name: minio_access_key
              valueFrom:
                secretKeyRef:
                  name: web3eye-minio
                  key: accesskey
            - name: minio_secret_key
              valueFrom:
                secretKeyRef:
                  name: web3eye-minio
                  key: secretkey
      volumes:
        - name: service-config
          configMap:
            name: dealer-config
---
apiVersion: v1
kind: Service
metadata:
  name: dealer
  namespace: kube-system
spec:
  selector:
    app: dealer
  # clusterIP: None
  ports:
    - name: http
      port: 30160
      targetPort: 30160
    - name: grpc
      port: 30161
      targetPort: 30161
