version="0.0.1"

[nft-meta]
domain="nft-meta"
http-port=30100
grpc-port=30101
log-file="/var/log/nft-meta.log"
collection-name="nft_info_images"
description="this collection for nft-meta"

[block-etl]
domain="block-etl"
http-port=30110
grpc-port=30111
log-file="/var/log/block-etl.log"

[cloud-proxy]
domain="cloud-proxy"
http-port=30120
grpc-port=30121
log-file="/var/log/cloud-proxy.log"

[gateway]
domain="gateway"
http-port=30130
grpc-port=30131
log-file="/var/log/gateway.log"

[ranker]
domain="ranker"
http-port=30140
grpc-port=30141
log-file="/var/log/ranker.log"

[entrance]
domain="entrance"
http-port=30150
grpc-port=30151
log-file="/var/log/entrance.log"

[dealer]
domain="dealer"
ipfs-repo="/root/.ipfs"
orbit-repo="/root/.orbit"
http-port=30160
grpc-port=30161
log-file="/var/log/dealer.log"

[gen-car]
domain="gen-car"
http-port=30170
grpc-port=30171
data-dir="/tmp/gencar_data"
log-file="/var/log/gen-car.log"

[retriever]
domain="retriever"
ipfs-repo="/home/test/.ipfs-retr"
orbit-repo="/home/test/.orbit"
http-port=30180
grpc-port=30181
log-file="/var/log/retriever.log"

[image-converter]
address="http://image-converter:8080"
task-input-topic="image-converter-input"
task-output-topic="image-converter-output"

[mysql]
domain="mysql"
port=3306
user="root"
password="QARo5aA6zO"
database="nft_meta"

[redis]
address="redis-cluster-headless:6379"
password="default"

[milvus]
address="milvus:19530"

[kafka]
bootstrap-servers="kafka-headless:9092"

[minio]
address="http://web3eye-minio:9000"
access-key="YacNyvYLuQ1J3mMaCvMy"
secret-key="AIYvh7F5TlzxagPySkD5flSIZhLGssZ432UKNqMJ"
region="default"
token-image-bucket="token-image-bucket"


[eth]
wallets="https://goerli.infura.io/v3/ae1e603c17bd4a48818251f52a7970a8"

[ipfs]
http-gateway="https://ipfs.io/"
